### ISSUE TITLE
生成申查SQL有个小bug

### ISSUE THREAD

**Issue by wuyuanyong** [58daojia-dba/mysqlbinlog_flashback#1]
具体情况如下：
DB version:MySQL 5.6.29  64bit 社区版
OS: RHEL 6.4 x86_64

1、解析出来的SQL
[root@rac3 log]# cat save_data_dml_test_20161206_164530.sql 
#end_log_pos 1014  2016-12-06T16:42:36 1481013756 mysql-bin.000001;
insert into `_wuyong_keep_data_`(`bfr_sex`,`bfr_id`,`bfr_user_id`,`op_datetime`,`op`) values(None,1,2,'2016-12-06 16:42:36','delete');

2、说明
--sex字段如果有空值，对应的空值会被解析成None

3、执行插入会报如下错误，导致插入失败
mysql> insert into `_wuyong_keep_data_`(`bfr_sex`,`bfr_id`,`bfr_user_id`,`op_datetime`,`op`) values(None,1,2,'2016-12-06 16:42:36','delete');
ERROR 1054 (42S22): Unknown column 'None' in 'field list'

4、建议，将空值解析成null，即可避免这个问题的出现。
 mysql>insert into `_wuyong_keep_data_`(`bfr_sex`,`bfr_id`,`bfr_user_id`,`op_datetime`,`op`) values(null,1,2,'2016-12-06 16:42:36','delete');
Query OK, 1 row affected (0.11 sec)

**Comment by yilai123** [comment]
谢谢，正在修复

**Comment by yilai123** [comment]
已经修复，因为我们的生产环境比较严格，不能有null值，但是可以有缺省值，所以开始没发现这个bug,谢谢
